### PR TITLE
add appId configuration parameter

### PR DESCRIPTION
**Pull request by msvechla**
## Summary

add `appId` parameter to make this option configurable as well. See #51 

## Test plan

Unfortunately I was unable to test the changes locally with my fork, maybe you can take a look

### CODE REVIEW

**Comment by msvechla** [comment]
I think one issue is that currently, this will result in supplying `appId=null` to algolia when no `appId` is specified. So we could set the current `appId` as a default. Or do you have a better idea?

**Comment by msvechla** [comment]
I updated the PR to set the default value of `appId` to the current value upstream

**Comment by gregberge** [comment]
Thanks!

**Comment by msvechla** [comment]
Thanks a lot for merging this. Could you also release a new version, please? This is kind of blocking us at the moment to use this awesome theme internally.

Thanks a lot!

**Comment by gregberge** [comment]
@msvechla done, sorry for the lonnggg delay!

**Pull request merged**
